#+begin_src emacs-lisp

  ;;; jv-basic-edit.el --- Some basic text editing commands  -*- lexical-binding:t; -*-


  ;; Author: Janne Väisänen <janva415@gmail.com>
  ;; Created 26 Mar 2022
  ;; Version: 0.1

  ;; Keywords: elisp, textediting
  ;; URL:

  ;;; Commentary

  ;; This package provides the minor mode jv-basic-edit. It's a minimal package ;; consisting of a feew basic text editing commands such as copy whole line.  ;; This file is not part of GNU Emacs. This was part of me learning Elisp and how minor mode are built. Feel free to copy but be aware the code herein has its flaws and there are probably better solutions out there.

  ;; This file is free sofware...

  ;;;###autoload

  #+end_src

;;; Code:
  
** Creating   a minor mode
Turning your code/package into a minor mode  could  be done using  the =define-minor-mode= mode macro. But to get a better understanding  of how minor modes work and are setup I decided to do it manually. To do so you need a bit of boilerplate code  following a few conventions (hence the macro).
We need

- a variable naming the mode ending with =-mode=
- a function with same name as variable (ELisp has different namespaces for functions and variables)

  That's really are all that is needed to create minor mode but in addition we can also   
   
- Enable keymaps by adding entries in =minor-mode-map-alist=. Entries in the list are  pairs of minor-mode symbols and keymaps.
- Enable hooks by creating  variable  with following convention =modename-mode-hook=.  This could initially be set to nil. running the hooks can be done using =run-hooks=
 - enable lighter for minor-mode-alist again using minor mode variable symbol and

Minor modes can be global or associtiated with specific buffer.  In case you want to to be associated with local buffer we need to make the minor-mode variable buffer local. This could be done using the =make-variable-buffer-local= command. I've comment out that part in the below code as i wanted this minor-mode to be global.  I left the comment so you can se how you could define the mode variable and make it buffer local in one shot.

#+begin_src emacs-lisp
;; (make-variable-buffer-local
(defvar jv-basic-edit-mode nil "Toggle jv-edit-basic-mode")
;; )
#+end_src

#+begin_src emacs-lisp
(defvar jv-basic-edit-mode-map (make-sparse-keymap) "The keymap for jv-edit-basic-mode")
#+end_src

;; Hooks on attached to this list will be run whenever mode is activated/deactivated
#+begin_src emacs-lisp
(defvar jv-basic-edit-mode-hook nil "The hook for jv-basic-edit-mode")
#+end_src


#+begin_src emacs-lisp
(define-key jv-basic-edit-mode-map (kbd "C-<return>") 'open-newline)
(define-key jv-basic-edit-mode-map (kbd "M-S-<down>") 'duplicate-line-down )
(define-key jv-basic-edit-mode-map (kbd "M-S-<up>" ) 'duplicate-line-up)
(define-key jv-basic-edit-mode-map (kbd "M-<down>")'swapline-down )
(define-key jv-basic-edit-mode-map (kbd "M-<up>")  'swapline-up )

;;register keybingings map (associate with this mode) 
(add-to-list 'minor-mode-map-alist ( cons 'jv-basic-edit-mode jv-basic-edit-mode-map))

#+end_src

#+begin_src emacs-lisp
;;register minor mode
(add-to-list 'minor-mode-alist '(jv-basic-edit-mode " jv-basic-edit"))
#+end_src

#+begin_src emacs-lisp
(defun jv-basic-edit-mode (&optional ARG)
  "jv-basic-edit-mode is a minor mode consisting of a few basic editing commands. If ARG positive number > 0  activate mode else deactivate.If ARG is 'toggle then toggle mode"
  (interactive (list 'toggle))
  (setq jv-basic-edit-mode
	(if (eq ARG 'toggle)
	    (not jv-basic-edit-mode)
	  (> ARG 0)))
  (if jv-basic-edit-mode
      (message "jv-basic-mode activated")
    (message "jv-basic-mode deactivated"))
  (run-hooks 'jv-basic-edit-mode-hook))
#+end_src 

** The commands
#+begin_src emacs-lisp
(defun open-newline (&optional n)
  "Opens a new line below current line even if cursor is in middle of current line.Move point to opened line. If N is set open n lines."
  (interactive "pNumber of lines to open: ")
  (goto-char (line-end-position))
	     (newline (or n 1)))
#+end_src

#+begin_src emacs-lisp
;; maybe refactor...
(defun copy-line ()
"Copy line(s) into kill-ring. "
(let ((beg (line-beginning-position))
      (end (line-end-position)))
    (save-excursion 
    (when mark-active
     (if (> (point) (mark))
 	 (setq beg (save-excursion (goto-char (mark)) (line-beginning-position)))
       (setq end (save-excursion (goto-char (mark)) (line-end-position)))))
     (copy-region-as-kill beg end))))
#+end_src

#+begin_src emacs-lisp
  (defun duplicate--line (&optional direction)
    "Duplicates line(s) of text in DIRECTION. if DIRECTION is 1  duplicate to line bellow else duplicate to line abbove current line." 
    (save-mark-and-excursion
      (copy-line)
      (open-newline)
      (yank))
    (when (eq direction 1)
      (next-line)))

  ;;Fixme only works once for selected region since loosing the marked area when doing next line
  (defun duplicate-line-down  ()
    "Creates newline(s) containing content of current line(s) below the current line. "
    (interactive)
    (duplicate--line 1))

(defun duplicate-line-up  ()
  "Creates  newline(s) containing content of current line(s) above the current line. "
  (interactive)
    (duplicate--line))
#+end_src

;; could cause problems on last line of buffer
;; could take advantage of exchange-point and mark?
;; beg and end delimits  single line at this point it might be first
;; (if point < mark) or last if (point > mark)
;; If point is after mark then end is correct but beg is beginnging of last line
;; mark is looking at characther on first line
;; if mark is after point end is currently last of first line and mark is at last line
#+begin_src emacs-lisp
(defun jv/kill--lines ()
  "Kill whole line(s). If mark is set kill all (whole)lines within region else kill line wher point is. "
  (let ((beg (line-beginning-position))
	(end (+ 1 (line-end-position))))
    (when mark-active
      (if (> (point)(mark))
	  (setq beg (save-excursion (goto-char (mark))(line-beginning-position)))
	(setq end (save-excursion (goto-char (mark)) (+ (line-end-position) 1)))))
    (kill-region beg end))
  )
#+end_src

;;Similar to finally clause. If next-line tries to go beyon end of buffer
  ;; We still want to yank back the killed line. 
#+begin_src emacs-lisp
;; FIXME region is lost when command is executed through keybindings. Hence can do it repeatadly
;; FIXME should barf on readonly buffers
(defun swapline-down ()
  "Transposes whole line(s) down. POINT is set to begining of moved line."
  (interactive)
  (jv/kill--lines)
  (unwind-protect
      (next-line)
    (progn 
      (beginning-of-line)
      ;; preserve current point
      (save-mark-and-excursion(yank)))))
#+end_src

#+begin_src emacs-lisp
(defun swapline-up ()
  "Transpose line(s) up."
  (interactive)
  (jv/kill--lines)
  (unwind-protect

      (previous-line)
    (progn
      (beginning-of-line)
      (save-mark-and-excursion(yank))
  )))
#+end_src

#+begin_src emacs-lisp
(provide 'jv-basic-edit)
#+end_src>

#+begin_src emacs-lisp
;;; jv-basic-edit.el ends here
#+end_src
